// utils/downloadHelper.ts
import jsPDF from "jspdf";

export const downloadProgressFile = (
    player: any,
    playerRank: number,
    playerLevel: number,
    stars: number,
    badge: string
) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(33, 37, 41);
    doc.setFont("helvetica", "bold");
    doc.text("📊 Progress Report", pageWidth / 2, 20, { align: "center" });

    // Draw background card
    doc.setFillColor(240, 248, 255); // Light card background
    doc.roundedRect(15, 30, pageWidth - 30, 100, 5, 5, "F");

    // Card title
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text("Player Summary", 20, 40);

    // Content
    const entries = [
        ["👤 Name", player?.Player_name ?? "N/A"],
        ["📈 Ranking", playerRank],
        ["🏆 Points Earned", player?.Playerpoint ?? 0],
        ["🎮 Level", playerLevel],
        ["🔥 Streak", `${player?.streak ?? 0} Days`],
        ["⭐ Stars", stars],
        ["🏅 Badge", badge || "None"],
        ["📆 Last Login", player?.lastLogin ?? "N/A"],
    ];

    let y = 50;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(34, 34, 34);

    for (const [label, value] of entries) {
        doc.text(`${label}:`, 22, y);
        doc.text(String(value), 80, y);
        y += 10;
    }

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Guhuza Quiz App", pageWidth / 2, 140, {
        align: "center",
    });

    doc.save("progress_report.pdf");
};
